version: '3.1'
services :
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: developia

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8081:8080





      