# Generated by Django 4.1.5 on 2023-02-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestProduct',
        ),
    ]
