# Generated by Django 4.1.5 on 2023-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='linkedin',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
