# Generated by Django 4.1.5 on 2023-02-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting_linkedin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutOurShop',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='WhoWeAre',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
