# Generated by Django 4.1.5 on 2023-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliveryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='deliveryinfo/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
