# Generated by Django 4.1.5 on 2023-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliveryinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secureshopping',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secureshopping',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secureshopping',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secureshopping',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
