# Generated by Django 4.1.5 on 2023-03-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deliveryinfo_text_az_deliveryinfo_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='ourservices/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Our Services',
            },
        ),
    ]
