# Generated by Django 4.1.5 on 2023-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ourservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
