# Generated by Django 4.1.5 on 2023-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutourshop_contact_privacypolicy_secureshopping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='paymentitem',
            field=models.ImageField(default=' ', upload_to='media/payment'),
            preserve_default=False,
        ),
    ]
