# Generated by Django 4.1.5 on 2023-03-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_privacypolicy_options_privacypolicy_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('title_az', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('text', models.TextField()),
                ('text_az', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='faq/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
