# Generated by Django 4.1.5 on 2023-01-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
