# Generated by Django 4.1.5 on 2023-01-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact_is_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/about_us')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aboutus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
