# Generated by Django 4.1.5 on 2023-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(default=1, upload_to='author/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
