# Generated by Django 4.1.5 on 2023-02-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'BlogCategory'},
        ),
    ]
