# Generated by Django 4.1.5 on 2023-02-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
