# Generated by Django 4.1.5 on 2023-03-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
